project_id = "idcapdxkvjuzzmytorhc"

[functions.create-payment]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.customer-support]
verify_jwt = false

[functions.send-followup-teaser]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
